api/urls.py
from . import views
from django.urls import path
# RestFrameWork Simple JWT
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

app_name = "api"

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("", views.get_routes, name="route_demo"),
    path("projects/", views.get_projects, name="get_projects"),
    path("projects/<str:pk>/", views.get_project, name="get_project"),
    path("projects/<str:pk>/vote/", views.project_vote, name="project_vote"),
    path("remove-tag/", views.remove_tag, name="remove_tag"),
]

django_2021/urls.py
from django.contrib import admin
from django.urls import path, include

# Django Auth Views
from django.contrib.auth import views as auth_views

# static media urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("projects/", include("projects.urls", namespace="projects")),
    path("", include("users.urls", namespace="users")),
    path("api/", include("api.urls", namespace="api")),
    # Auth paths
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.projects, name="projects"),
    path("project/<str:pk>/", views.project, name="project"),
    path("create-project/", views.create_project, name="create-project"),
    path("update-project/<str:pk>/", views.update_project, name="update-project"),
    path("delete-project/<str:pk>/", views.delete_project, name="delete-project"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.profiles, name="profiles"),
    path("profile/<str:pk>/", views.user_profile, name="user_profile"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logut"),
    path("register/", views.register_user, name="register"),
    path("account/", views.user_account, name="account"),
    path("edit-account/", views.edit_account, name="edit_account"),
    path("create-skill/", views.create_skill, name="create_skill"),
    path("update-skill/<str:pk>/", views.update_skill, name="update_skill"),
    path("delete-skill/<str:pk>/", views.delete_skill, name="delete_skill"),
    path("inbox/", views.inbox, name="inbox"),
    path("inbox/message/<str:pk>/", views.view_message, name="message"),
    path("send-message/<str:pk>/", views.create_message, name="create_message"),
]

templates/includes/navbar.html
{% load static %}
<header class="header">
    <div class="container container--narrow">
        <a href="{% url 'users:profiles' %}" class="header__logo">
            <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo"/>
        </a>
        <nav class="header__nav">
            <input type="checkbox" id="responsive-menu"/>
            <label for="responsive-menu" class="toggle-menu">
                <span>Menu</span>
                <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
                <li class="header__menuItem"><a href="{% url 'users:profiles' %}">Developers</a></li>
                <li class="header__menuItem"><a href="{% url 'projects:projects' %}">Projects</a></li>
                {% if request.user.is_authenticated %}
                    <li class="header__menuItem"><a href="{% url 'users:inbox' %} ">Inbox</a></li>
                    <li class="header__menuItem"><a href="{% url 'users:account' %}">Account</a></li>
                    <li class="header__menuItem">
                        <a href="{% url 'users:logut' %}" class="btn btn--sub">Logout</a>
                    </li>
                {% else %}
                    <li class="header__menuItem">
                        <a href="{% url 'users:login' %}" class="btn btn--sub">Login/Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

templates/includes/pagination.html
{% if queryset.has_other_pages %}
    <div class="pagination">
        <ul class="container">
            {% if queryset.has_previous and queryset.number > 5 %}
                <li>
                    <a class="btn page-link"
                       href="?page=1" data-page="1">
                        &#10094; &#10094;
                    </a>
                </li>
            {% endif %}
            {% if queryset.has_previous %}
                <li>
                    <a class="btn page-link"
                       href="?page={{ queryset.previous_page_number }}" data-page="{{ queryset.previous_page_number }}">
                        &#10094; Prev
                    </a>
                </li>
            {% endif %}
            {% for page in custom_range %}
                <li>
                    <a class="btn page-link {% if page == queryset.number %} btn--sub {% endif %}"
                       href="?page={{ page }}" data-page="{{ page }}">
                        {{ page }}
                    </a>
                </li>
            {% endfor %}
            {% if queryset.has_next %}
                <li>
                    <a class="btn page-link"
                       href="?page={{ queryset.next_page_number }}" data-page="{{ queryset.next_page_number }}">
                        Next &#10095;
                    </a>
                </li>
                <li>
                    <a class="btn page-link"
                       href="?page={{ queryset.paginator.num_pages }}" data-page="{{ queryset.paginator.num_pages }}">
                        &#10095; &#10095;
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

templates/includes/socials.html
{% if profile.social_github %}
    <li>
        <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im
                                    im-github"></i></a>
    </li>
{% endif %}

{% if profile.social_twitter %}
    <li>
        <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i
                class="im im-twitter"></i></a>
    </li>
{% endif %}

{% if profile.social_linkedin %}
    <li>
        <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i
                class="im im-linkedin"></i></a>
    </li>
{% endif %}

{% if profile.social_youtube %}
    <li>
        <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i
                class="im im-youtube"></i></a>
    </li>
{% endif %}

{% if profile.social_facebook %}
    <li>
        <a title="Facebook" href="{{ profile.social_facebook }}" target="_blank"><i
                class="im im-facebook"></i></a>
    </li>
{% endif %}

{% if profile.social_website %}
    <li>
        <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i
                class="im im-globe"></i></a>
    </li>
{% endif %}