api/urls.py
from . import views
from django.urls import path
# RestFrameWork Simple JWT
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

app_name = "api"

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("", views.get_routes, name="route_demo"),
    path("projects/", views.get_projects, name="get_projects"),
    path("projects/<str:pk>/", views.get_project, name="get_project"),
    path("projects/<str:pk>/vote/", views.project_vote, name="project_vote"),
    path("remove-tag/", views.remove_tag, name="remove_tag"),
]

django_2021/urls.py
from django.contrib import admin
from django.urls import path, include

# Django Auth Views
from django.contrib.auth import views as auth_views

# static media urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("projects/", include("projects.urls", namespace="projects")),
    path("", include("users.urls", namespace="users")),
    path("api/", include("api.urls", namespace="api")),
    # Auth paths
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.projects, name="projects"),
    path("project/<str:pk>/", views.project, name="project"),
    path("create-project/", views.create_project, name="create-project"),
    path("update-project/<str:pk>/", views.update_project, name="update-project"),
    path("delete-project/<str:pk>/", views.delete_project, name="delete-project"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.profiles, name="profiles"),
    path("profile/<str:pk>/", views.user_profile, name="user_profile"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logut"),
    path("register/", views.register_user, name="register"),
    path("account/", views.user_account, name="account"),
    path("edit-account/", views.edit_account, name="edit_account"),
    path("create-skill/", views.create_skill, name="create_skill"),
    path("update-skill/<str:pk>/", views.update_skill, name="update_skill"),
    path("delete-skill/<str:pk>/", views.delete_skill, name="delete_skill"),
    path("inbox/", views.inbox, name="inbox"),
    path("inbox/message/<str:pk>/", views.view_message, name="message"),
    path("send-message/<str:pk>/", views.create_message, name="create_message"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


# Create your models here.
class Project(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_img = models.ImageField(null=True, blank=True, default="default.jpg", verbose_name="Featured Image")
    demo_link = models.URLField(max_length=2000, null=True, blank=True, verbose_name="Demo Link")
    source_link = models.URLField(max_length=2000, null=True, blank=True, verbose_name="Source Link")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField("Tag", blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        if len(self.title) < 25:
            return self.title
        else:
            return f"{self.title[:25]}..."


    class Meta:
        ordering = ["-vote_ratio", "-vote_total", "title"]


    @property
    def image_url(self):
        try:
            url = self.featured_img.url
        except:
            url = ""
        return url

    @property
    def reviewers(self):
        query_set = self.review_set.all().values_list("owner__id", flat=True)
        return query_set

    @property
    def get_vote_count(self):
        reviews = self.review_set.all()
        up_votes = reviews.filter(value="up").count()
        total_votes = reviews.count()
        ratio = (up_votes / total_votes) * 100
        self.vote_total = total_votes
        self.vote_ratio = ratio
        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ("up", "Up Vote"),
        ("down", "Down Vote"),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    class Meta:
        unique_together = [["owner", "project"]]


    def __str__(self):
        if len(self.value) < 25:
            return self.value
        else:
            return f"{self.value[:25]}..."


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        if len(self.name) < 25:
            return self.name
        else:
            return f"{self.name[:25]}..."

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    username = models.CharField(max_length=200, blank=True, null=True, unique=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, blank=True, null=True, unique=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True, verbose_name="Intro")
    bio = models.TextField(blank=True, null=True)
    profile_img = models.ImageField(null=True, blank=True, upload_to="profiles/",
                                    default="profiles/user-default.png", verbose_name="Avatar")
    social_github = models.URLField(max_length=200, null=True, blank=True, verbose_name="Github",
                                    help_text="https://github.com/USERNAME")
    social_twitter = models.URLField(max_length=200, null=True, blank=True,
                                     verbose_name="Twitter", help_text="https://twitter.com/USERNAME")
    social_facebook = models.URLField(max_length=200, null=True, blank=True, verbose_name="Facebook",
                                      help_text="https://facebook.com/YOUR.NAME.1234")
    social_linkedin = models.URLField(max_length=200, null=True, blank=True, verbose_name="Linkedin",

                                      help_text="https://tr.linkedin.com/in/USERNAME-1234")
    social_youtube = models.URLField(max_length=200, null=True, blank=True, verbose_name="Youtube Channel",
                                     help_text="https://www.youtube.com/c/YOURCHANNELNAME")
    social_website = models.URLField(max_length=200, null=True, blank=True, verbose_name="Personal Website")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    class Meta:
        ordering = ("-created",)


    def __str__(self):
        return str(self.username)

    @property
    def image_url(self):
        try:
            url = self.profile_img.url
        except:
            url = ""
        return url


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name[:10])


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.subject


    class Meta:
        ordering = ["is_read", "-created"]

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password1", "password2")


    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        # self.fields["title"].widget.attrs.update({"class": "input", "placeholder": "Add title"})
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input input--text"})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        exclude = ("user",)


    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input input--text", "placeholder": field.help_text})


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = "__all__"
        exclude = ("owner",)


    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input input--text"})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["name", "email", "subject", "body"]


    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}
{% block body %}
    <main class="settingsPage profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <div class="card text-center">
                        <div class="card__body dev">
                            <a class="tag tag--pill tag--main settings__btn" href="
{% url 'users:edit_account' %}?back=/account/"><i
                                    class="im im-edit"></i>
                                Edit</a>
                            {% if profile.image_url %}
                                <img class="avatar avatar--xl dev__avatar" src="{{ profile.image_url }}" alt="Avatar"/>
                            {% else %}
                                <img class="avatar avatar--xl dev__avatar" src=
                                        "{% static 'images/profiles/user-default.jpg' %}"
                                     alt="Avatar"/>
                            {% endif %}
                            <h2 class="dev__name">{{ profile.name }}</h2>
                            <p class="dev__title">{{ profile.short_intro }}</p>
                            <p class="dev__location">{{ profile.location }}</p>
                            <ul class="dev__social">
                                {% include "includes/socials.html" %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">
                            {{ profile.bip }}
                        </p>
                    </div>
                    <div class="settings">
                        <h3 class="settings__title">Skills</h3>
                        <a class="tag tag--pill tag--sub settings__btn tag--lg" href="
{% url 'users:create_skill' %}?back=/account/"><i
                                class="im 
                        im-plus"></i> Add
                            Skill</a>
                    </div>

                    <table class="settings__table">
                        {% for skill in skills %}
                            <tr>
                                <td class="settings__tableInfo">
                                    <h4>{{ skill.name }}</h4>
                                    <p>
                                        {{ skill.description }}
                                    </p>
                                </td>
                                <td class="settings__tableActions">
                                    <a class="tag tag--pill tag--main settings__btn"
                                       href="{% url 'users:update_skill' skill.id %}?back=/account/"><i class="im
                                    im-edit"></i>
                                        Edit</a>
                                    <a class="tag tag--pill tag--main settings__btn"
                                       href="{% url 'users:delete_skill' skill.id %}?back=/account/"><i
                                            class="im im-x-mark-circle-o"></i>
                                        Delete</a>
                                </td>
                            </tr>
                        {% endfor %}

                    </table>

                    <div class="settings">
                        <h3 class="settings__title">Projects</h3>
                        <a class="tag tag--pill tag--sub settings__btn tag--lg"
                           href="{% url 'projects:create-project' %}?back=/account/"><i class="im
                        im-plus"></i> Add
                            Project</a>
                    </div>

                    <table class="settings__table">
                        {% for project in projects %}
                            <tr>
                                <td class="settings__thumbnail">
                                    <a href="{% url 'projects:project' project.id %}">
                                        {% if project.image_url %}
                                            <img src="{{ project.image_url }}" alt="Project Thumbnail"/>
                                        {% else %}
                                            <img src="{% static 'images/default.jpg' %}" alt="Project Thumbnail"/>
                                        {% endif %}
                                    </a>

                                </td>
                                <td class="settings__tableInfo">
                                    <a href="{% url 'projects:project' project.id %}">{{ project.title }}</a>
                                    <p>
                                        {{ project.description|slice:"150" }}
                                        {% if project.description|length > 150 %}
                                            ...
                                        {% endif %}

                                    </p>
                                </td>
                                <td class="settings__tableActions">
                                    <a class="tag tag--pill tag--main settings__btn"
                                       href="{% url 'projects:update-project' project.id %}?back=/account/"><i
                                            class="im
                                    im-edit"></i>
                                        Edit</a>
                                    <a class="tag tag--pill tag--main settings__btn"
                                       href="{% url 'projects:delete-project' project.id %}?back=/account/"><i
                                            class="im im-x-mark-circle-o"></i>
                                        Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block body %}
    {% if page == "register" %}
        <div class="auth">
            <div class="card">
                <div class="auth__header text-center">
                    <a href="{% url 'users:profiles' %}">
                        <img src="{% static 'images/icon.svg' %}" alt="icon"/>
                    </a>
                    <h3>Register an Account</h3>
                    <p>Create a new developer account</p>
                </div>

                <form action="{% url 'users:register' %}" method="POST" class="form auth__form">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#text">{{ field.label }}</label>
                            {{ field }}
                            {#                            {% if field.help_text %}#}
                            {#                                <small>{{ field.help_text }}</small>#}
                            {#                            {% endif %}#}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p style="color: red;">{{ error }}</p>
                                {% endfor %}


                            {% endif %}
                        </div>
                    {% endfor %}

                    <div class="auth__actions">
                        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In"/>
                    </div>
                </form>

                <div class="auth__alternative">
                    <p>Already have an Account?</p>
                    <a href="{% url 'users:login' %}">Log In</a>
                </div>
            </div>
        </div>

    {% else %}
        <div class="auth">
            <div class="card">
                <div class="auth__header text-center">
                    <a href="{% url 'users:profiles' %}">
                        <img src="{% static 'images/icon.svg' %}" alt="icon"/>
                    </a>
                    <h3>Account Login</h3>
                    <p>Hello Developer, Welcome Back!</p>
                </div>

                <form action="" method="POST" class="form auth__form">
                    {% csrf_token %}
                    <!-- Input:Username -->
                    <div class="form__field">
                        <label for="formInput#text">Username: </label>
                        <input
                                class="input input--text"
                                id="formInput#text"
                                type="text"
                                name="username"
                                placeholder="Enter your username..."
                        />
                    </div>

                    <!-- Input:Password -->
                    <div class="form__field">
                        <label for="formInput#password">Password: </label>
                        <input
                                class="input input--password"
                                id="formInput#passowrd"
                                type="password"
                                name="password"
                                placeholder="••••••••"
                        />
                    </div>
                    <div class="auth__actions">
                        <input class="btn btn--sub btn--lg" type="submit" value="Log In"/>
                        <a href="{% url 'reset_password' %}">Forget Password?</a>
                    </div>
                </form>
                <div class="auth__alternative">
                    <p>Don’t have an Account?</p>
                    <a href="{% url 'users:register' %}">Sign Up</a>

                </div>
            </div>
        </div>

    {% endif %}
{% endblock %}

users/templates/users/profiles.html
{% extends 'main.html' %}
{% load static %}
{% block body %}
    <main class="home">
        <section class="hero-section text-center">
            <div class="container container--narrow">
                <div class="hero-section__box">
                    <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                    <h2>FROM AROUND THE WORLD</h2>
                </div>
                <div class="hero-section__search">
                    <form id="search-form" class="form" action="{% url 'users:profiles' %}" method="get">
                        <div class="form__field">
                            <label for="formInput#search">Search Developers </label>
                            <input class="input input--text" id="formInput#search" type="text" value="
{{ search_query }}"
                                   name="search_query"
                                   placeholder="Search by developer name"/>
                        </div>
                        <input class="btn btn--sub btn--lg" type="submit" value="Search"/>
                    </form>
                </div>
            </div>
        </section>
        <!-- Search Result: DevList -->
        <section class="devlist">
            <div class="container">
                <div class="grid grid--three">
                    {% for profile in profiles %}
                        <div class="column card">
                            <div class="dev">
                                <a href="{% url 'users:user_profile' profile.id %}" class="card__body">
                                    <div class="dev__profile">

                                        {% if profile.image_url %}
                                            <img class="avatar avatar--md" src="{{ profile.image_url }}" alt="Avatar"/>
                                        {% else %}
                                            <img class="avatar avatar--md" src=
                                                    "{% static 'images/profiles/user-default.jpg' %}"
                                                 alt="Avatar"/>
                                        {% endif %}

                                        <div class="dev__meta">
                                            <h3>{{ profile.name|slice:"20" }}</h3>
                                            <h5>{{ profile.short_intro|slice:"40" }}</h5>
                                        </div>
                                    </div>
                                    <p class="dev__info">
                                        {{ profile.bio|slice:"150" }}
                                    </p>
                                    <div class="dev__skills">
                                        {% for skill in profile.skill_set.all %}
                                            <span class="tag tag--pill tag--main">
                                                <small>{{ skill }}</small>
                                            </span>
                                        {% endfor %}
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        {% include "includes/pagination.html" with queryset=profiles custom_range=custom_range %}
    </main>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'main.html' %}
{% load static %}
{% block body %}
    <main class="profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <div class="card text-center">
                        <div class="card__body dev">
                            {% if profile.image_url %}
                                <img class="avatar avatar--xl" src="{{ profile.image_url }}" alt="Avatar"/>
                            {% else %}
                                <img class="avatar avatar--xl" src=
                                        "{% static 'images/profiles/user-default.jpg' %}"
                                     alt="Avatar"/>
                            {% endif %}
                            <h2 class="dev__name">{{ profile.name }}</h2>
                            <p class="dev__title">{{ profile.short_intro }}</p>
                            <p class="dev__location">{{ profile.location }}</p>
                            <ul class="dev__social">
                                {% include "includes/socials.html" %}
                            </ul>
                            {% if request.user.profile.id != profile.id %}
                                <a href="{% url 'users:create_message' profile.id %}" class="btn btn--sub btn--lg">Send
                                    Message </a>
                            {% endif %}

                        </div>
                    </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">
                            {{ profile.bio }}
                        </p>
                    </div>
                    <div class="devInfo">
                        <h3 class="devInfo__title">Skills</h3>
                        <div class="devInfo__skills">
                            {% for topSkill in topSkills %}
                                <div class="devSkill">
                                    <h4 class="devSkill__title">{{ topSkill.name }}</h4>
                                    <p class="devSkill__info">
                                        {{ topSkill.description }}
                                    </p>
                                </div>
                            {% endfor %}
                            <h3 class="devInfo__subtitle">Other Skills</h3>
                            <div class="devInfo__otherSkills">
                                {% for otherSkill in otherSkills %}
                                    <span class="tag tag--pill tag--sub tag--lg">
                                        <small>{{ otherSkill.name }}</small>
                                    </span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="devInfo">
                        <h3 class="devInfo__title">Projects</h3>
                        <div class="grid grid--two">
                            {% for project in profile.project_set.all %}
                                <div class="column">
                                    <div class="card project">
                                        <a href="{% url 'projects:project' project.id %}" class="project">
                                            {% if project.image_url %}
                                                <img class="project__thumbnail" src="{{ project.image_url }}"
                                                     alt="Project Thumbnail"/>
                                            {% else %}
                                                <img class="project__thumbnail" src="{% static 'images/default.jpg' %}"
                                                     alt="Project Thumbnail"/>
                                            {% endif %}
                                            <div class="card__body">
                                                <h3 class="project__title">{{ project.title }}</h3>
                                                <p><a class="project__author"
                                                      href="{% url 'users:user_profile' project.owner.id %}">By
                                                    {{ project.owner.name }}</a>
                                                </p>
                                                <p class="project--rating">
                                                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span>
                                                    Postitive
                                                    Feedback ({{ project.vote_total }}
                                                    Vote{{ project.vote_total|pluralize:"s" }})
                                                </p>
                                                <div class="project__tags">
                                                    {% for tag in project.tags.all %}
                                                        <span class="tag tag--pill tag--main">
                                                          <small>{{ tag }}</small>
                                                        </span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}